### PR TITLE
Fixed steps to run locally on Windows

### PR DESCRIPTION
**Pull request by Alhaji-trujillo**
I made suitable changes to the ReadMe for effectively running the app locally on Windows

### CODE REVIEW

**Comment by keenanjohnson** [comment]
@Alhaji-trujillo I don't actually think this is correct? Windows uses "\" not "/" as you have changed it here?

@yuzhang0302 has already verified these instructions on her Windows machine, did they not work for you? Can you confirm what terminal you are using in Windows?

**Comment by Alhaji-trujillo** [comment]
Previous codes in the ReadMe didn't work for me. I use git bash on VS code.
Usually, Windows uses frontslash(/) to navigate paths in terminal and not backslash(\). It was the first thing I realised when I wanted to run the "activate" script

**Comment by keenanjohnson** [comment]
Ah got it. I think what we should do is have two different windows sections then: one for Git Bash on Windows and one for the Normal Windows console. Can you edit the readme to reflect that instead? Thanks for all your help!

**Comment by Alhaji-trujillo** [comment]
Okay def! will close and repull
Can you check slack? I tagged you in our build-sprint channel on InfluxDB

**Comment by Alhaji-trujillo** [comment]
Done @keenanjohnson

**Comment by keenanjohnson** [comment]
Can you leave the previous instructions as well, just labeled for the standard windows cmd prompt?

**Comment by Alhaji-trujillo** [comment]
I didn't remove the previous instructions. I just made two guides for Windows
image

**Comment by keenanjohnson** [comment]
Ah my mistake. I misread the diff. Looks good!

**Comment by keenanjohnson** [comment]
@all-contributors please add @Alhaji-trujillo  for his help improving the docs!

**Pull request merged**
