### PR TITLE
Added loading icon for when graphs update

### PR DESCRIPTION
**Pull request by rishikavikondala**
Completed #32

### CODE REVIEW

**Review by keenanjohnson — CHANGES_REQUESTED** [review]
This looks pretty good @rishikavikondala ! Looks like you have mastered the PR workflow, so good job!

When I run this code locally, an interesting side effect occurs where the duration is printed below the dropdown now. I suspect that's because we are creating a new div for the loading icon and when it's gone, this is in it's place?

image

Also it would be nice to display the icon for the full duration of the queries, not just for a hardcoded value? Does that seem possible?

Thanks again!

**Comment by rishikavikondala** [comment]
@keenanjohnson - fixed both the issues you specified!

**Comment by keenanjohnson** [comment]
Thanks very much! Taking a look now!

**Review by keenanjohnson — APPROVED** [review]
Looks good!

**Comment by keenanjohnson** [comment]
@all-contributors please add @rishikavikondala for their awesome help with the code.

**Pull request merged**
