### PR TITLE
Better map style and color palette

### PR DESCRIPTION
**Pull request by brianstrauch**
Switched to a better-looking map style, unified the color palette (green sensor dots and loading animations), and centered the loading animations.

Screen Shot 2021-09-22 at 9 37 46 PM

### CODE REVIEW

**Comment by keenanjohnson** [comment]
Hey @brianstrauch thanks for the changeset!  I really like the new tileset :).

When I run this locally, I don't see the loading icons at all. Do you see them on your end? Also, I'm down for the new color scale, but I'd like to keep the legend on the side if possible.

**Comment by brianstrauch** [comment]
My bad, forgot to commit the loading gif. I'll fix this up later!

**Comment by keenanjohnson** [comment]
All good!

**Comment by brianstrauch** [comment]
Fixed!

**Comment by keenanjohnson** [comment]
Awesome @brianstrauch ! This looks great!

**Pull request merged**
